CWindow1::CWindow1(void)
{
  SetFOwner(this);
  SetName("window1");
  SetTag(0);
  SetX(290);
  SetY(104);
  SetWidth(401);
  SetHeight(439);
  SetHint("(null)");
  SetEnable(1);
  SetVisible(1);
  SetPoupMenu(NULL);
  SetTitle("getlinks");
  //filedialog1
  filedialog1.SetFOwner(this);
  filedialog1.SetName("filedialog1");
  filedialog1.SetTag(0);
  filedialog1.SetX(81);
  filedialog1.SetY(90);
  filedialog1.SetWidth(200);
  filedialog1.SetHeight(250);
  filedialog1.SetHint("");
  filedialog1.SetEnable(1);
  filedialog1.SetVisible(0);
  filedialog1.SetPoupMenu(NULL);
  //list1
  list1.SetFOwner(this);
  list1.SetName("list1");
  list1.SetTag(0);
  list1.SetX(12);
  list1.SetY(93);
  list1.SetWidth(378);
  list1.SetHeight(300);
  list1.SetHint("");
  list1.SetEnable(1);
  list1.SetVisible(1);
  list1.SetPoupMenu(NULL);
  list1.SetItens("");
  CreateChild(& list1);
  //button1
  button1.SetFOwner(this);
  button1.SetName("button1");
  button1.SetTag(0);
  button1.SetX(20);
  button1.SetY(9);
  button1.SetWidth(160);
  button1.SetHeight(20);
  button1.SetHint("");
  button1.SetEnable(1);
  button1.SetVisible(1);
  button1.SetPoupMenu(NULL);
  button1.MouseButtonClick=MOUSEBUTTONCLICK & CWindow1::button1_MouseButtonClick;
  button1.SetText("Choose One File");
  CreateChild(& button1);
  //button2
  button2.SetFOwner(this);
  button2.SetName("button2");
  button2.SetTag(0);
  button2.SetX(213);
  button2.SetY(9);
  button2.SetWidth(160);
  button2.SetHeight(20);
  button2.SetHint("");
  button2.SetEnable(1);
  button2.SetVisible(1);
  button2.SetPoupMenu(NULL);
  button2.MouseButtonClick=MOUSEBUTTONCLICK & CWindow1::button2_MouseButtonClick;
  button2.SetText("Save List To File");
  CreateChild(& button2);
  //edit1
  edit1.SetFOwner(this);
  edit1.SetName("edit1");
  edit1.SetTag(0);
  edit1.SetX(112);
  edit1.SetY(38);
  edit1.SetWidth(260);
  edit1.SetHeight(20);
  edit1.SetHint("");
  edit1.SetEnable(1);
  edit1.SetVisible(1);
  edit1.SetPoupMenu(NULL);
  edit1.SetText("");
  CreateChild(& edit1);
  //string2
  string2.SetFOwner(this);
  string2.SetName("string2");
  string2.SetTag(0);
  string2.SetX(26);
  string2.SetY(38);
  string2.SetWidth(80);
  string2.SetHeight(20);
  string2.SetHint("");
  string2.SetEnable(1);
  string2.SetVisible(1);
  string2.SetPoupMenu(NULL);
  string2.SetText("Base Address");
  CreateChild(& string2);
  //button3
  button3.SetFOwner(this);
  button3.SetName("button3");
  button3.SetTag(0);
  button3.SetX(17);
  button3.SetY(406);
  button3.SetWidth(160);
  button3.SetHeight(20);
  button3.SetHint("");
  button3.SetEnable(1);
  button3.SetVisible(1);
  button3.SetPoupMenu(NULL);
  button3.MouseButtonClick=MOUSEBUTTONCLICK & CWindow1::button3_MouseButtonClick;
  button3.SetText("Download All");
  CreateChild(& button3);
  //button4
  button4.SetFOwner(this);
  button4.SetName("button4");
  button4.SetTag(0);
  button4.SetX(229);
  button4.SetY(407);
  button4.SetWidth(160);
  button4.SetHeight(20);
  button4.SetHint("");
  button4.SetEnable(1);
  button4.SetVisible(1);
  button4.SetPoupMenu(NULL);
  button4.MouseButtonClick=MOUSEBUTTONCLICK & CWindow1::button4_MouseButtonClick;
  button4.SetText("Remove Selected");
  CreateChild(& button4);
};
