#!/bin/sh

prefix=/usr
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: lxrad_SDL2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs] [--static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 0.8
      ;;
    --cflags)
      if test ${prefix}/include != /usr/include ; then
          # Handle oddities in Win32 path handling (assumes prefix)
          prefix=`echo ${prefix} | sed 's,^//\([A-Z]\),\1:,'`

          includes=-I${prefix}/include
      fi
      echo $includes -I${prefix}/include/lxrad_SDL2/ -Wall -ggdb
      ;;
    --cxxflags)
      if test ${prefix}/include != /usr/include ; then
          # Handle oddities in Win32 path handling (assumes prefix)
          prefix=`echo ${prefix} | sed 's,^//\([A-Z]\),\1:,'`

          includes=-I${prefix}/include
      fi
      echo $includes -I${prefix}/include/lxrad_SDL2/ -Wall -ggdb
      ;;
    --libs|--plugin-libs|--library-libs)
      libdirs="-L${exec_prefix}/lib "
      echo $libdirs -llxrad_SDL2 -lSDL2_ttf -lSDL2_image -lSDL2  -lSDL2 -lSDL2_image -lSDL2_ttf 
      ;;
    --static-libs)
#    --libs|--static-libs)
      libdirs="-L${exec_prefix}/lib "
      echo $libdirs -llxrad_SDL2 -lSDL2_ttf -lSDL2_image -lSDL2  -lSDL2 -lSDL2_image -lSDL2_ttf
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
