CWindow1::CWindow1(void)
{
  SetFOwner(this);
  SetName("window1");
  SetTag(0);
  SetX(311);
  SetY(212);
  SetWidth(331);
  SetHeight(169);
  SetHint("(null)");
  SetEnable(1);
  SetVisible(1);
  SetPopupMenu(NULL);
  EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::_MouseButtonPress;
  SetTitle("simple");
  //pmenu1
  pmenu1.SetFOwner(this);
  pmenu1.SetName("pmenu1");
  pmenu1.SetTag(0);
  pmenu1.SetX(14);
  pmenu1.SetY(62);
  pmenu1.SetWidth(10);
  pmenu1.SetHeight(1);
  pmenu1.SetHint("");
  pmenu1.SetEnable(1);
  pmenu1.SetVisible(0);
  pmenu1.SetMenuItems("Exit,");
  CreateChild(& pmenu1);
  //button2
  button2.SetFOwner(this);
  button2.SetName("button2");
  button2.SetTag(0);
  button2.SetX(109);
  button2.SetY(87);
  button2.SetWidth(60);
  button2.SetHeight(20);
  button2.SetHint("Sub");
  button2.SetEnable(1);
  button2.SetVisible(1);
  button2.SetPopupMenu(NULL);
  button2.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::button2_MouseButtonPress;
  button2.SetText("Sub");
  CreateChild(& button2);
  //button3
  button3.SetFOwner(this);
  button3.SetName("button3");
  button3.SetTag(0);
  button3.SetX(177);
  button3.SetY(87);
  button3.SetWidth(60);
  button3.SetHeight(20);
  button3.SetHint("Mul");
  button3.SetEnable(1);
  button3.SetVisible(1);
  button3.SetPopupMenu(NULL);
  button3.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::button3_MouseButtonPress;
  button3.SetText("Mul");
  CreateChild(& button3);
  //button4
  button4.SetFOwner(this);
  button4.SetName("button4");
  button4.SetTag(0);
  button4.SetX(243);
  button4.SetY(87);
  button4.SetWidth(60);
  button4.SetHeight(20);
  button4.SetHint("Div");
  button4.SetEnable(1);
  button4.SetVisible(1);
  button4.SetPopupMenu(NULL);
  button4.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::button4_MouseButtonPress;
  button4.SetText("Div");
  CreateChild(& button4);
  //edit1
  edit1.SetFOwner(this);
  edit1.SetName("edit1");
  edit1.SetTag(0);
  edit1.SetX(41);
  edit1.SetY(50);
  edit1.SetWidth(60);
  edit1.SetHeight(20);
  edit1.SetHint("");
  edit1.SetEnable(1);
  edit1.SetVisible(1);
  edit1.SetPopupMenu(NULL);
  edit1.SetText("");
  CreateChild(& edit1);
  //edit2
  edit2.SetFOwner(this);
  edit2.SetName("edit2");
  edit2.SetTag(0);
  edit2.SetX(139);
  edit2.SetY(50);
  edit2.SetWidth(60);
  edit2.SetHeight(20);
  edit2.SetHint("");
  edit2.SetEnable(1);
  edit2.SetVisible(1);
  edit2.SetPopupMenu(NULL);
  edit2.SetText("");
  CreateChild(& edit2);
  //edit3
  edit3.SetFOwner(this);
  edit3.SetName("edit3");
  edit3.SetTag(0);
  edit3.SetX(240);
  edit3.SetY(50);
  edit3.SetWidth(60);
  edit3.SetHeight(20);
  edit3.SetHint("");
  edit3.SetEnable(1);
  edit3.SetVisible(1);
  edit3.SetPopupMenu(NULL);
  edit3.SetText("");
  CreateChild(& edit3);
  //string1
  string1.SetFOwner(this);
  string1.SetName("string1");
  string1.SetTag(0);
  string1.SetX(103);
  string1.SetY(51);
  string1.SetWidth(30);
  string1.SetHeight(20);
  string1.SetHint("");
  string1.SetEnable(1);
  string1.SetVisible(1);
  string1.SetPopupMenu(NULL);
  string1.SetText("?");
  CreateChild(& string1);
  //string2
  string2.SetFOwner(this);
  string2.SetName("string2");
  string2.SetTag(0);
  string2.SetX(202);
  string2.SetY(52);
  string2.SetWidth(30);
  string2.SetHeight(20);
  string2.SetHint("");
  string2.SetEnable(1);
  string2.SetVisible(1);
  string2.SetPopupMenu(NULL);
  string2.SetText("=");
  CreateChild(& string2);
  //button5
  button5.SetFOwner(this);
  button5.SetName("button5");
  button5.SetTag(0);
  button5.SetX(142);
  button5.SetY(133);
  button5.SetWidth(60);
  button5.SetHeight(20);
  button5.SetHint("Exit Application");
  button5.SetEnable(1);
  button5.SetVisible(1);
  button5.SetPopupMenu(NULL);
  button5.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::button5_MouseButtonPress;
  button5.SetText("Exit");
  CreateChild(& button5);
  //menu1
  menu1.SetFOwner(this);
  menu1.SetName("menu1");
  menu1.SetTag(0);
  menu1.SetX(0);
  menu1.SetY(0);
  menu1.SetWidth(331);
  menu1.SetHeight(25);
  menu1.SetHint("");
  menu1.SetEnable(1);
  menu1.SetVisible(1);
  menu1.SetMenuItems("File,About,");
  CreateChild(& menu1);
  //button1
  button1.SetFOwner(this);
  button1.SetName("button1");
  button1.SetTag(0);
  button1.SetX(41);
  button1.SetY(87);
  button1.SetWidth(60);
  button1.SetHeight(20);
  button1.SetHint("Add");
  button1.SetEnable(1);
  button1.SetVisible(1);
  button1.SetPopupMenu(NULL);
  button1.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::button1_MouseButtonPress;
  button1.SetText("Add");
  CreateChild(& button1);
  //pmenu1_Exit
  pmenu1_Exit.SetFOwner(this);
  pmenu1_Exit.SetName("pmenu1_Exit");
  pmenu1_Exit.SetTag(0);
  pmenu1_Exit.SetText("Exit");
  pmenu1_Exit.SetSubMenu(NULL);
  pmenu1_Exit.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::pmenu1_Exit_MouseButtonPress;
  pmenu1.CreateChild(& pmenu1_Exit);
  //menu1_File
  menu1_File.SetFOwner(this);
  menu1_File.SetName("menu1_File");
  menu1_File.SetTag(0);
  menu1_File.SetText("File");
  menu1_File.SetSubMenu(&pmenu1);
  menu1.CreateChild(& menu1_File);
  //menu1_About
  menu1_About.SetFOwner(this);
  menu1_About.SetName("menu1_About");
  menu1_About.SetTag(0);
  menu1_About.SetText("About");
  menu1_About.SetSubMenu(NULL);
  menu1_About.EvMouseButtonPress=EVMOUSEBUTTONPRESS & CWindow1::menu1_About_MouseButtonPress;
  menu1.CreateChild(& menu1_About);
};
