#ifndef CWINDOW1 
#define CWINDOW1

#include<lxrad/lxrad.h>

class CWindow1:public CWindow
{
  public:
  /*#Controls*/
  CPMenu pmenu1;
  CToolButton toolbutton1;
  CToolButton toolbutton2;
  CToolButton toolbutton3;
  CToolButton toolbutton4;
  CToolButton toolbutton5;
  CToolButton toolbutton6;
  CToolButton toolbutton7;
  CToolButton toolbutton8;
  CToolButton toolbutton9;
  CToolButton toolbutton10;
  CToolButton toolbutton11;
  CToolButton toolbutton12;
  CToolButton toolbutton13;
  CToolButton toolbutton14;
  CToolButton toolbutton15;
  CToolButton toolbutton16;
  CToolButton toolbutton17;
  CToolButton toolbutton18;
  CToolButton toolbutton19;
  CToolButton toolbutton20;
  CToolButton toolbutton21;
  CToolButton toolbutton22;
  CToolButton toolbutton23;
  CToolButton toolbutton24;
  CToolButton toolbutton25;
  CToolButton toolbutton26;
  CToolButton toolbutton27;
  CToolButton toolbutton28;
  CToolButton toolbutton29;
  CToolButton toolbutton30;
  CToolButton toolbutton31;
  CToolButton toolbutton32;
  CToolButton toolbutton33;
  CToolButton toolbutton34;
  CToolButton toolbutton35;
  CToolButton toolbutton36;
  CToolButton toolbutton37;
  CToolButton toolbutton38;
  CToolButton toolbutton39;
  CToolButton toolbutton40;
  CToolButton toolbutton41;
  CToolButton toolbutton42;
  CToolButton toolbutton43;
  CToolButton toolbutton44;
  CToolButton toolbutton45;
  CToolButton toolbutton46;
  CToolButton toolbutton47;
  CToolButton toolbutton48;
  CToolButton toolbutton49;
  CToolButton toolbutton50;
  CToolButton toolbutton51;
  CToolButton toolbutton52;
  CToolButton toolbutton53;
  CToolButton toolbutton54;
  CToolButton toolbutton55;
  CToolButton toolbutton56;
  CToolButton toolbutton57;
  CToolButton toolbutton58;
  CToolButton toolbutton59;
  CToolButton toolbutton60;
  CToolButton toolbutton61;
  CToolButton toolbutton62;
  CToolButton toolbutton63;
  CToolButton toolbutton64;
  CToolButton toolbutton65;
  CToolButton toolbutton66;
  CToolButton toolbutton67;
  CToolButton toolbutton68;
  CToolButton toolbutton69;
  CToolButton toolbutton70;
  CToolButton toolbutton71;
  CToolButton toolbutton72;
  CToolButton toolbutton73;
  CToolButton toolbutton74;
  CToolButton toolbutton75;
  CToolButton toolbutton76;
  CToolButton toolbutton77;
  CToolButton toolbutton78;
  CToolButton toolbutton79;
  CToolButton toolbutton80;
  CToolButton toolbutton81;
  CToolButton toolbutton82;
  CToolButton toolbutton83;
  CToolButton toolbutton84;
  CToolButton toolbutton85;
  CToolButton toolbutton86;
  CToolButton toolbutton87;
  CToolButton toolbutton88;
  CToolButton toolbutton89;
  CToolButton toolbutton90;
  CToolButton toolbutton91;
  CToolButton toolbutton92;
  CToolButton toolbutton93;
  CToolButton toolbutton94;
  CToolButton toolbutton95;
  CToolButton toolbutton96;
  CToolButton toolbutton97;
  CToolButton toolbutton98;
  CToolButton toolbutton99;
  CToolButton toolbutton100;
  CMenu menu1;
  CItemMenu menu1_Arquivo;
  CItemMenu menu1_Limpar;
  CItemMenu menu1_Sobre;
  CItemMenu pmenu1_Abrir;
  CItemMenu pmenu1_Salvar;
  CItemMenu pmenu1_Sair;
  CFileDialog abrirdialog;
  CFileDialog salvardialog;
  /*#Events*/
  void _OnCreate(CControl * control);
  void toolbutton1_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton2_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton3_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton4_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton5_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton6_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton7_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton8_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton9_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton10_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton11_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton12_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton13_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton14_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton15_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton16_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton17_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton18_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton19_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton20_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton21_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton22_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton23_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton24_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton25_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton26_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton27_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton28_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton29_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton30_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton31_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton32_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton33_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton34_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton35_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton36_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton37_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton38_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton39_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton40_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton41_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton42_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton43_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton44_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton45_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton46_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton47_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton48_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton49_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton50_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton51_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton52_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton53_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton54_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton55_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton56_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton57_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton58_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton59_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton60_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton61_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton62_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton63_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton64_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton65_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton66_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton67_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton68_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton69_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton70_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton71_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton72_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton73_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton74_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton75_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton76_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton77_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton78_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton79_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton80_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton81_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton82_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton83_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton84_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton85_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton86_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton87_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton88_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton89_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton90_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton91_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton92_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton93_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton94_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton95_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton96_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton97_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton98_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton99_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void toolbutton100_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void menu1_Limpar_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void menu1_Sobre_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void pmenu1_Abrir_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void pmenu1_Salvar_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  void pmenu1_Sair_MouseButtonPress(CControl * control, uint button, uint x, uint y,uint state);
  /*#Others*/
  CWindow1(void);
  void toolbuttonMouseButtonPress(CControl* control,uint button,uint x,uint y,uint mask);
};
 extern CWindow1 Window1 ;

#endif /*#CWINDOW1*/

