CWindow1::CWindow1(void)
{
  SetFOwner(this);
  SetName("window1");
  SetTag(0);
  SetX(289);
  SetY(153);
  SetWidth(290);
  SetHeight(316);
  SetHint("(null)");
  SetEnable(1);
  SetVisible(1);
  SetPoupMenu(NULL);
  SetTitle("Editor");
  OnCreate=ONCREATE & CWindow1::_OnCreate;
  //pmenu1
  pmenu1.SetFOwner(this);
  pmenu1.SetName("pmenu1");
  pmenu1.SetTag(0);
  pmenu1.SetX(46);
  pmenu1.SetY(28);
  pmenu1.SetWidth(10);
  pmenu1.SetHeight(1);
  pmenu1.SetHint("");
  pmenu1.SetEnable(1);
  pmenu1.SetVisible(0);
  pmenu1.SetMenuItens("Abrir,Salvar,Sair,");
  CreateChild(& pmenu1);
  //toolbutton1
  toolbutton1.SetFOwner(this);
  toolbutton1.SetName("toolbutton1");
  toolbutton1.SetTag(0);
  toolbutton1.SetX(10);
  toolbutton1.SetY(35);
  toolbutton1.SetWidth(26);
  toolbutton1.SetHeight(26);
  toolbutton1.SetHint("");
  toolbutton1.SetEnable(1);
  toolbutton1.SetVisible(1);
  toolbutton1.SetPoupMenu(NULL);
  toolbutton1.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton1_MouseButtonPress;
  toolbutton1.SetPixmapFileName("");
  CreateChild(& toolbutton1);
  //toolbutton2
  toolbutton2.SetFOwner(this);
  toolbutton2.SetName("toolbutton2");
  toolbutton2.SetTag(1);
  toolbutton2.SetX(37);
  toolbutton2.SetY(35);
  toolbutton2.SetWidth(26);
  toolbutton2.SetHeight(26);
  toolbutton2.SetHint("");
  toolbutton2.SetEnable(1);
  toolbutton2.SetVisible(1);
  toolbutton2.SetPoupMenu(NULL);
  toolbutton2.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton2_MouseButtonPress;
  toolbutton2.SetPixmapFileName("");
  CreateChild(& toolbutton2);
  //toolbutton3
  toolbutton3.SetFOwner(this);
  toolbutton3.SetName("toolbutton3");
  toolbutton3.SetTag(2);
  toolbutton3.SetX(64);
  toolbutton3.SetY(35);
  toolbutton3.SetWidth(26);
  toolbutton3.SetHeight(26);
  toolbutton3.SetHint("");
  toolbutton3.SetEnable(1);
  toolbutton3.SetVisible(1);
  toolbutton3.SetPoupMenu(NULL);
  toolbutton3.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton3_MouseButtonPress;
  toolbutton3.SetPixmapFileName("");
  CreateChild(& toolbutton3);
  //toolbutton4
  toolbutton4.SetFOwner(this);
  toolbutton4.SetName("toolbutton4");
  toolbutton4.SetTag(3);
  toolbutton4.SetX(91);
  toolbutton4.SetY(35);
  toolbutton4.SetWidth(26);
  toolbutton4.SetHeight(26);
  toolbutton4.SetHint("");
  toolbutton4.SetEnable(1);
  toolbutton4.SetVisible(1);
  toolbutton4.SetPoupMenu(NULL);
  toolbutton4.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton4_MouseButtonPress;
  toolbutton4.SetPixmapFileName("");
  CreateChild(& toolbutton4);
  //toolbutton5
  toolbutton5.SetFOwner(this);
  toolbutton5.SetName("toolbutton5");
  toolbutton5.SetTag(4);
  toolbutton5.SetX(118);
  toolbutton5.SetY(35);
  toolbutton5.SetWidth(26);
  toolbutton5.SetHeight(26);
  toolbutton5.SetHint("");
  toolbutton5.SetEnable(1);
  toolbutton5.SetVisible(1);
  toolbutton5.SetPoupMenu(NULL);
  toolbutton5.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton5_MouseButtonPress;
  toolbutton5.SetPixmapFileName("");
  CreateChild(& toolbutton5);
  //toolbutton6
  toolbutton6.SetFOwner(this);
  toolbutton6.SetName("toolbutton6");
  toolbutton6.SetTag(5);
  toolbutton6.SetX(145);
  toolbutton6.SetY(35);
  toolbutton6.SetWidth(26);
  toolbutton6.SetHeight(26);
  toolbutton6.SetHint("");
  toolbutton6.SetEnable(1);
  toolbutton6.SetVisible(1);
  toolbutton6.SetPoupMenu(NULL);
  toolbutton6.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton6_MouseButtonPress;
  toolbutton6.SetPixmapFileName("");
  CreateChild(& toolbutton6);
  //toolbutton7
  toolbutton7.SetFOwner(this);
  toolbutton7.SetName("toolbutton7");
  toolbutton7.SetTag(6);
  toolbutton7.SetX(172);
  toolbutton7.SetY(35);
  toolbutton7.SetWidth(26);
  toolbutton7.SetHeight(26);
  toolbutton7.SetHint("");
  toolbutton7.SetEnable(1);
  toolbutton7.SetVisible(1);
  toolbutton7.SetPoupMenu(NULL);
  toolbutton7.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton7_MouseButtonPress;
  toolbutton7.SetPixmapFileName("");
  CreateChild(& toolbutton7);
  //toolbutton8
  toolbutton8.SetFOwner(this);
  toolbutton8.SetName("toolbutton8");
  toolbutton8.SetTag(7);
  toolbutton8.SetX(199);
  toolbutton8.SetY(35);
  toolbutton8.SetWidth(26);
  toolbutton8.SetHeight(26);
  toolbutton8.SetHint("");
  toolbutton8.SetEnable(1);
  toolbutton8.SetVisible(1);
  toolbutton8.SetPoupMenu(NULL);
  toolbutton8.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton8_MouseButtonPress;
  toolbutton8.SetPixmapFileName("");
  CreateChild(& toolbutton8);
  //toolbutton9
  toolbutton9.SetFOwner(this);
  toolbutton9.SetName("toolbutton9");
  toolbutton9.SetTag(8);
  toolbutton9.SetX(226);
  toolbutton9.SetY(35);
  toolbutton9.SetWidth(26);
  toolbutton9.SetHeight(26);
  toolbutton9.SetHint("");
  toolbutton9.SetEnable(1);
  toolbutton9.SetVisible(1);
  toolbutton9.SetPoupMenu(NULL);
  toolbutton9.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton9_MouseButtonPress;
  toolbutton9.SetPixmapFileName("");
  CreateChild(& toolbutton9);
  //toolbutton10
  toolbutton10.SetFOwner(this);
  toolbutton10.SetName("toolbutton10");
  toolbutton10.SetTag(9);
  toolbutton10.SetX(253);
  toolbutton10.SetY(35);
  toolbutton10.SetWidth(26);
  toolbutton10.SetHeight(26);
  toolbutton10.SetHint("");
  toolbutton10.SetEnable(1);
  toolbutton10.SetVisible(1);
  toolbutton10.SetPoupMenu(NULL);
  toolbutton10.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton10_MouseButtonPress;
  toolbutton10.SetPixmapFileName("");
  CreateChild(& toolbutton10);
  //toolbutton11
  toolbutton11.SetFOwner(this);
  toolbutton11.SetName("toolbutton11");
  toolbutton11.SetTag(10);
  toolbutton11.SetX(10);
  toolbutton11.SetY(62);
  toolbutton11.SetWidth(26);
  toolbutton11.SetHeight(26);
  toolbutton11.SetHint("");
  toolbutton11.SetEnable(1);
  toolbutton11.SetVisible(1);
  toolbutton11.SetPoupMenu(NULL);
  toolbutton11.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton11_MouseButtonPress;
  toolbutton11.SetPixmapFileName("");
  CreateChild(& toolbutton11);
  //toolbutton12
  toolbutton12.SetFOwner(this);
  toolbutton12.SetName("toolbutton12");
  toolbutton12.SetTag(11);
  toolbutton12.SetX(37);
  toolbutton12.SetY(62);
  toolbutton12.SetWidth(26);
  toolbutton12.SetHeight(26);
  toolbutton12.SetHint("");
  toolbutton12.SetEnable(1);
  toolbutton12.SetVisible(1);
  toolbutton12.SetPoupMenu(NULL);
  toolbutton12.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton12_MouseButtonPress;
  toolbutton12.SetPixmapFileName("");
  CreateChild(& toolbutton12);
  //toolbutton13
  toolbutton13.SetFOwner(this);
  toolbutton13.SetName("toolbutton13");
  toolbutton13.SetTag(12);
  toolbutton13.SetX(64);
  toolbutton13.SetY(62);
  toolbutton13.SetWidth(26);
  toolbutton13.SetHeight(26);
  toolbutton13.SetHint("");
  toolbutton13.SetEnable(1);
  toolbutton13.SetVisible(1);
  toolbutton13.SetPoupMenu(NULL);
  toolbutton13.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton13_MouseButtonPress;
  toolbutton13.SetPixmapFileName("");
  CreateChild(& toolbutton13);
  //toolbutton14
  toolbutton14.SetFOwner(this);
  toolbutton14.SetName("toolbutton14");
  toolbutton14.SetTag(13);
  toolbutton14.SetX(91);
  toolbutton14.SetY(62);
  toolbutton14.SetWidth(26);
  toolbutton14.SetHeight(26);
  toolbutton14.SetHint("");
  toolbutton14.SetEnable(1);
  toolbutton14.SetVisible(1);
  toolbutton14.SetPoupMenu(NULL);
  toolbutton14.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton14_MouseButtonPress;
  toolbutton14.SetPixmapFileName("");
  CreateChild(& toolbutton14);
  //toolbutton15
  toolbutton15.SetFOwner(this);
  toolbutton15.SetName("toolbutton15");
  toolbutton15.SetTag(14);
  toolbutton15.SetX(118);
  toolbutton15.SetY(62);
  toolbutton15.SetWidth(26);
  toolbutton15.SetHeight(26);
  toolbutton15.SetHint("");
  toolbutton15.SetEnable(1);
  toolbutton15.SetVisible(1);
  toolbutton15.SetPoupMenu(NULL);
  toolbutton15.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton15_MouseButtonPress;
  toolbutton15.SetPixmapFileName("");
  CreateChild(& toolbutton15);
  //toolbutton16
  toolbutton16.SetFOwner(this);
  toolbutton16.SetName("toolbutton16");
  toolbutton16.SetTag(15);
  toolbutton16.SetX(145);
  toolbutton16.SetY(62);
  toolbutton16.SetWidth(26);
  toolbutton16.SetHeight(26);
  toolbutton16.SetHint("");
  toolbutton16.SetEnable(1);
  toolbutton16.SetVisible(1);
  toolbutton16.SetPoupMenu(NULL);
  toolbutton16.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton16_MouseButtonPress;
  toolbutton16.SetPixmapFileName("");
  CreateChild(& toolbutton16);
  //toolbutton17
  toolbutton17.SetFOwner(this);
  toolbutton17.SetName("toolbutton17");
  toolbutton17.SetTag(16);
  toolbutton17.SetX(172);
  toolbutton17.SetY(62);
  toolbutton17.SetWidth(26);
  toolbutton17.SetHeight(26);
  toolbutton17.SetHint("");
  toolbutton17.SetEnable(1);
  toolbutton17.SetVisible(1);
  toolbutton17.SetPoupMenu(NULL);
  toolbutton17.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton17_MouseButtonPress;
  toolbutton17.SetPixmapFileName("");
  CreateChild(& toolbutton17);
  //toolbutton18
  toolbutton18.SetFOwner(this);
  toolbutton18.SetName("toolbutton18");
  toolbutton18.SetTag(17);
  toolbutton18.SetX(199);
  toolbutton18.SetY(62);
  toolbutton18.SetWidth(26);
  toolbutton18.SetHeight(26);
  toolbutton18.SetHint("");
  toolbutton18.SetEnable(1);
  toolbutton18.SetVisible(1);
  toolbutton18.SetPoupMenu(NULL);
  toolbutton18.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton18_MouseButtonPress;
  toolbutton18.SetPixmapFileName("");
  CreateChild(& toolbutton18);
  //toolbutton19
  toolbutton19.SetFOwner(this);
  toolbutton19.SetName("toolbutton19");
  toolbutton19.SetTag(18);
  toolbutton19.SetX(226);
  toolbutton19.SetY(62);
  toolbutton19.SetWidth(26);
  toolbutton19.SetHeight(26);
  toolbutton19.SetHint("");
  toolbutton19.SetEnable(1);
  toolbutton19.SetVisible(1);
  toolbutton19.SetPoupMenu(NULL);
  toolbutton19.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton19_MouseButtonPress;
  toolbutton19.SetPixmapFileName("");
  CreateChild(& toolbutton19);
  //toolbutton20
  toolbutton20.SetFOwner(this);
  toolbutton20.SetName("toolbutton20");
  toolbutton20.SetTag(19);
  toolbutton20.SetX(253);
  toolbutton20.SetY(62);
  toolbutton20.SetWidth(26);
  toolbutton20.SetHeight(26);
  toolbutton20.SetHint("");
  toolbutton20.SetEnable(1);
  toolbutton20.SetVisible(1);
  toolbutton20.SetPoupMenu(NULL);
  toolbutton20.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton20_MouseButtonPress;
  toolbutton20.SetPixmapFileName("");
  CreateChild(& toolbutton20);
  //toolbutton21
  toolbutton21.SetFOwner(this);
  toolbutton21.SetName("toolbutton21");
  toolbutton21.SetTag(20);
  toolbutton21.SetX(10);
  toolbutton21.SetY(89);
  toolbutton21.SetWidth(26);
  toolbutton21.SetHeight(26);
  toolbutton21.SetHint("");
  toolbutton21.SetEnable(1);
  toolbutton21.SetVisible(1);
  toolbutton21.SetPoupMenu(NULL);
  toolbutton21.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton21_MouseButtonPress;
  toolbutton21.SetPixmapFileName("");
  CreateChild(& toolbutton21);
  //toolbutton22
  toolbutton22.SetFOwner(this);
  toolbutton22.SetName("toolbutton22");
  toolbutton22.SetTag(21);
  toolbutton22.SetX(37);
  toolbutton22.SetY(89);
  toolbutton22.SetWidth(26);
  toolbutton22.SetHeight(26);
  toolbutton22.SetHint("");
  toolbutton22.SetEnable(1);
  toolbutton22.SetVisible(1);
  toolbutton22.SetPoupMenu(NULL);
  toolbutton22.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton22_MouseButtonPress;
  toolbutton22.SetPixmapFileName("");
  CreateChild(& toolbutton22);
  //toolbutton23
  toolbutton23.SetFOwner(this);
  toolbutton23.SetName("toolbutton23");
  toolbutton23.SetTag(22);
  toolbutton23.SetX(64);
  toolbutton23.SetY(89);
  toolbutton23.SetWidth(26);
  toolbutton23.SetHeight(26);
  toolbutton23.SetHint("");
  toolbutton23.SetEnable(1);
  toolbutton23.SetVisible(1);
  toolbutton23.SetPoupMenu(NULL);
  toolbutton23.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton23_MouseButtonPress;
  toolbutton23.SetPixmapFileName("");
  CreateChild(& toolbutton23);
  //toolbutton24
  toolbutton24.SetFOwner(this);
  toolbutton24.SetName("toolbutton24");
  toolbutton24.SetTag(23);
  toolbutton24.SetX(91);
  toolbutton24.SetY(89);
  toolbutton24.SetWidth(26);
  toolbutton24.SetHeight(26);
  toolbutton24.SetHint("");
  toolbutton24.SetEnable(1);
  toolbutton24.SetVisible(1);
  toolbutton24.SetPoupMenu(NULL);
  toolbutton24.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton24_MouseButtonPress;
  toolbutton24.SetPixmapFileName("");
  CreateChild(& toolbutton24);
  //toolbutton25
  toolbutton25.SetFOwner(this);
  toolbutton25.SetName("toolbutton25");
  toolbutton25.SetTag(24);
  toolbutton25.SetX(118);
  toolbutton25.SetY(89);
  toolbutton25.SetWidth(26);
  toolbutton25.SetHeight(26);
  toolbutton25.SetHint("");
  toolbutton25.SetEnable(1);
  toolbutton25.SetVisible(1);
  toolbutton25.SetPoupMenu(NULL);
  toolbutton25.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton25_MouseButtonPress;
  toolbutton25.SetPixmapFileName("");
  CreateChild(& toolbutton25);
  //toolbutton26
  toolbutton26.SetFOwner(this);
  toolbutton26.SetName("toolbutton26");
  toolbutton26.SetTag(25);
  toolbutton26.SetX(145);
  toolbutton26.SetY(89);
  toolbutton26.SetWidth(26);
  toolbutton26.SetHeight(26);
  toolbutton26.SetHint("");
  toolbutton26.SetEnable(1);
  toolbutton26.SetVisible(1);
  toolbutton26.SetPoupMenu(NULL);
  toolbutton26.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton26_MouseButtonPress;
  toolbutton26.SetPixmapFileName("");
  CreateChild(& toolbutton26);
  //toolbutton27
  toolbutton27.SetFOwner(this);
  toolbutton27.SetName("toolbutton27");
  toolbutton27.SetTag(26);
  toolbutton27.SetX(172);
  toolbutton27.SetY(89);
  toolbutton27.SetWidth(26);
  toolbutton27.SetHeight(26);
  toolbutton27.SetHint("");
  toolbutton27.SetEnable(1);
  toolbutton27.SetVisible(1);
  toolbutton27.SetPoupMenu(NULL);
  toolbutton27.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton27_MouseButtonPress;
  toolbutton27.SetPixmapFileName("");
  CreateChild(& toolbutton27);
  //toolbutton28
  toolbutton28.SetFOwner(this);
  toolbutton28.SetName("toolbutton28");
  toolbutton28.SetTag(27);
  toolbutton28.SetX(199);
  toolbutton28.SetY(89);
  toolbutton28.SetWidth(26);
  toolbutton28.SetHeight(26);
  toolbutton28.SetHint("");
  toolbutton28.SetEnable(1);
  toolbutton28.SetVisible(1);
  toolbutton28.SetPoupMenu(NULL);
  toolbutton28.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton28_MouseButtonPress;
  toolbutton28.SetPixmapFileName("");
  CreateChild(& toolbutton28);
  //toolbutton29
  toolbutton29.SetFOwner(this);
  toolbutton29.SetName("toolbutton29");
  toolbutton29.SetTag(28);
  toolbutton29.SetX(226);
  toolbutton29.SetY(89);
  toolbutton29.SetWidth(26);
  toolbutton29.SetHeight(26);
  toolbutton29.SetHint("");
  toolbutton29.SetEnable(1);
  toolbutton29.SetVisible(1);
  toolbutton29.SetPoupMenu(NULL);
  toolbutton29.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton29_MouseButtonPress;
  toolbutton29.SetPixmapFileName("");
  CreateChild(& toolbutton29);
  //toolbutton30
  toolbutton30.SetFOwner(this);
  toolbutton30.SetName("toolbutton30");
  toolbutton30.SetTag(29);
  toolbutton30.SetX(253);
  toolbutton30.SetY(89);
  toolbutton30.SetWidth(26);
  toolbutton30.SetHeight(26);
  toolbutton30.SetHint("");
  toolbutton30.SetEnable(1);
  toolbutton30.SetVisible(1);
  toolbutton30.SetPoupMenu(NULL);
  toolbutton30.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton30_MouseButtonPress;
  toolbutton30.SetPixmapFileName("");
  CreateChild(& toolbutton30);
  //toolbutton31
  toolbutton31.SetFOwner(this);
  toolbutton31.SetName("toolbutton31");
  toolbutton31.SetTag(30);
  toolbutton31.SetX(10);
  toolbutton31.SetY(116);
  toolbutton31.SetWidth(26);
  toolbutton31.SetHeight(26);
  toolbutton31.SetHint("");
  toolbutton31.SetEnable(1);
  toolbutton31.SetVisible(1);
  toolbutton31.SetPoupMenu(NULL);
  toolbutton31.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton31_MouseButtonPress;
  toolbutton31.SetPixmapFileName("");
  CreateChild(& toolbutton31);
  //toolbutton32
  toolbutton32.SetFOwner(this);
  toolbutton32.SetName("toolbutton32");
  toolbutton32.SetTag(31);
  toolbutton32.SetX(37);
  toolbutton32.SetY(116);
  toolbutton32.SetWidth(26);
  toolbutton32.SetHeight(26);
  toolbutton32.SetHint("");
  toolbutton32.SetEnable(1);
  toolbutton32.SetVisible(1);
  toolbutton32.SetPoupMenu(NULL);
  toolbutton32.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton32_MouseButtonPress;
  toolbutton32.SetPixmapFileName("");
  CreateChild(& toolbutton32);
  //toolbutton33
  toolbutton33.SetFOwner(this);
  toolbutton33.SetName("toolbutton33");
  toolbutton33.SetTag(32);
  toolbutton33.SetX(64);
  toolbutton33.SetY(116);
  toolbutton33.SetWidth(26);
  toolbutton33.SetHeight(26);
  toolbutton33.SetHint("");
  toolbutton33.SetEnable(1);
  toolbutton33.SetVisible(1);
  toolbutton33.SetPoupMenu(NULL);
  toolbutton33.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton33_MouseButtonPress;
  toolbutton33.SetPixmapFileName("");
  CreateChild(& toolbutton33);
  //toolbutton34
  toolbutton34.SetFOwner(this);
  toolbutton34.SetName("toolbutton34");
  toolbutton34.SetTag(33);
  toolbutton34.SetX(91);
  toolbutton34.SetY(116);
  toolbutton34.SetWidth(26);
  toolbutton34.SetHeight(26);
  toolbutton34.SetHint("");
  toolbutton34.SetEnable(1);
  toolbutton34.SetVisible(1);
  toolbutton34.SetPoupMenu(NULL);
  toolbutton34.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton34_MouseButtonPress;
  toolbutton34.SetPixmapFileName("");
  CreateChild(& toolbutton34);
  //toolbutton35
  toolbutton35.SetFOwner(this);
  toolbutton35.SetName("toolbutton35");
  toolbutton35.SetTag(34);
  toolbutton35.SetX(118);
  toolbutton35.SetY(116);
  toolbutton35.SetWidth(26);
  toolbutton35.SetHeight(26);
  toolbutton35.SetHint("");
  toolbutton35.SetEnable(1);
  toolbutton35.SetVisible(1);
  toolbutton35.SetPoupMenu(NULL);
  toolbutton35.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton35_MouseButtonPress;
  toolbutton35.SetPixmapFileName("");
  CreateChild(& toolbutton35);
  //toolbutton36
  toolbutton36.SetFOwner(this);
  toolbutton36.SetName("toolbutton36");
  toolbutton36.SetTag(35);
  toolbutton36.SetX(145);
  toolbutton36.SetY(116);
  toolbutton36.SetWidth(26);
  toolbutton36.SetHeight(26);
  toolbutton36.SetHint("");
  toolbutton36.SetEnable(1);
  toolbutton36.SetVisible(1);
  toolbutton36.SetPoupMenu(NULL);
  toolbutton36.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton36_MouseButtonPress;
  toolbutton36.SetPixmapFileName("");
  CreateChild(& toolbutton36);
  //toolbutton37
  toolbutton37.SetFOwner(this);
  toolbutton37.SetName("toolbutton37");
  toolbutton37.SetTag(36);
  toolbutton37.SetX(172);
  toolbutton37.SetY(116);
  toolbutton37.SetWidth(26);
  toolbutton37.SetHeight(26);
  toolbutton37.SetHint("");
  toolbutton37.SetEnable(1);
  toolbutton37.SetVisible(1);
  toolbutton37.SetPoupMenu(NULL);
  toolbutton37.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton37_MouseButtonPress;
  toolbutton37.SetPixmapFileName("");
  CreateChild(& toolbutton37);
  //toolbutton38
  toolbutton38.SetFOwner(this);
  toolbutton38.SetName("toolbutton38");
  toolbutton38.SetTag(37);
  toolbutton38.SetX(199);
  toolbutton38.SetY(116);
  toolbutton38.SetWidth(26);
  toolbutton38.SetHeight(26);
  toolbutton38.SetHint("");
  toolbutton38.SetEnable(1);
  toolbutton38.SetVisible(1);
  toolbutton38.SetPoupMenu(NULL);
  toolbutton38.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton38_MouseButtonPress;
  toolbutton38.SetPixmapFileName("");
  CreateChild(& toolbutton38);
  //toolbutton39
  toolbutton39.SetFOwner(this);
  toolbutton39.SetName("toolbutton39");
  toolbutton39.SetTag(38);
  toolbutton39.SetX(226);
  toolbutton39.SetY(116);
  toolbutton39.SetWidth(26);
  toolbutton39.SetHeight(26);
  toolbutton39.SetHint("");
  toolbutton39.SetEnable(1);
  toolbutton39.SetVisible(1);
  toolbutton39.SetPoupMenu(NULL);
  toolbutton39.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton39_MouseButtonPress;
  toolbutton39.SetPixmapFileName("");
  CreateChild(& toolbutton39);
  //toolbutton40
  toolbutton40.SetFOwner(this);
  toolbutton40.SetName("toolbutton40");
  toolbutton40.SetTag(39);
  toolbutton40.SetX(253);
  toolbutton40.SetY(116);
  toolbutton40.SetWidth(26);
  toolbutton40.SetHeight(26);
  toolbutton40.SetHint("");
  toolbutton40.SetEnable(1);
  toolbutton40.SetVisible(1);
  toolbutton40.SetPoupMenu(NULL);
  toolbutton40.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton40_MouseButtonPress;
  toolbutton40.SetPixmapFileName("");
  CreateChild(& toolbutton40);
  //toolbutton41
  toolbutton41.SetFOwner(this);
  toolbutton41.SetName("toolbutton41");
  toolbutton41.SetTag(40);
  toolbutton41.SetX(10);
  toolbutton41.SetY(143);
  toolbutton41.SetWidth(26);
  toolbutton41.SetHeight(26);
  toolbutton41.SetHint("");
  toolbutton41.SetEnable(1);
  toolbutton41.SetVisible(1);
  toolbutton41.SetPoupMenu(NULL);
  toolbutton41.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton41_MouseButtonPress;
  toolbutton41.SetPixmapFileName("");
  CreateChild(& toolbutton41);
  //toolbutton42
  toolbutton42.SetFOwner(this);
  toolbutton42.SetName("toolbutton42");
  toolbutton42.SetTag(41);
  toolbutton42.SetX(37);
  toolbutton42.SetY(143);
  toolbutton42.SetWidth(26);
  toolbutton42.SetHeight(26);
  toolbutton42.SetHint("");
  toolbutton42.SetEnable(1);
  toolbutton42.SetVisible(1);
  toolbutton42.SetPoupMenu(NULL);
  toolbutton42.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton42_MouseButtonPress;
  toolbutton42.SetPixmapFileName("");
  CreateChild(& toolbutton42);
  //toolbutton43
  toolbutton43.SetFOwner(this);
  toolbutton43.SetName("toolbutton43");
  toolbutton43.SetTag(42);
  toolbutton43.SetX(64);
  toolbutton43.SetY(143);
  toolbutton43.SetWidth(26);
  toolbutton43.SetHeight(26);
  toolbutton43.SetHint("");
  toolbutton43.SetEnable(1);
  toolbutton43.SetVisible(1);
  toolbutton43.SetPoupMenu(NULL);
  toolbutton43.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton43_MouseButtonPress;
  toolbutton43.SetPixmapFileName("");
  CreateChild(& toolbutton43);
  //toolbutton44
  toolbutton44.SetFOwner(this);
  toolbutton44.SetName("toolbutton44");
  toolbutton44.SetTag(43);
  toolbutton44.SetX(91);
  toolbutton44.SetY(143);
  toolbutton44.SetWidth(26);
  toolbutton44.SetHeight(26);
  toolbutton44.SetHint("");
  toolbutton44.SetEnable(1);
  toolbutton44.SetVisible(1);
  toolbutton44.SetPoupMenu(NULL);
  toolbutton44.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton44_MouseButtonPress;
  toolbutton44.SetPixmapFileName("");
  CreateChild(& toolbutton44);
  //toolbutton45
  toolbutton45.SetFOwner(this);
  toolbutton45.SetName("toolbutton45");
  toolbutton45.SetTag(44);
  toolbutton45.SetX(118);
  toolbutton45.SetY(143);
  toolbutton45.SetWidth(26);
  toolbutton45.SetHeight(26);
  toolbutton45.SetHint("");
  toolbutton45.SetEnable(1);
  toolbutton45.SetVisible(1);
  toolbutton45.SetPoupMenu(NULL);
  toolbutton45.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton45_MouseButtonPress;
  toolbutton45.SetPixmapFileName("");
  CreateChild(& toolbutton45);
  //toolbutton46
  toolbutton46.SetFOwner(this);
  toolbutton46.SetName("toolbutton46");
  toolbutton46.SetTag(45);
  toolbutton46.SetX(145);
  toolbutton46.SetY(143);
  toolbutton46.SetWidth(26);
  toolbutton46.SetHeight(26);
  toolbutton46.SetHint("");
  toolbutton46.SetEnable(1);
  toolbutton46.SetVisible(1);
  toolbutton46.SetPoupMenu(NULL);
  toolbutton46.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton46_MouseButtonPress;
  toolbutton46.SetPixmapFileName("");
  CreateChild(& toolbutton46);
  //toolbutton47
  toolbutton47.SetFOwner(this);
  toolbutton47.SetName("toolbutton47");
  toolbutton47.SetTag(46);
  toolbutton47.SetX(172);
  toolbutton47.SetY(143);
  toolbutton47.SetWidth(26);
  toolbutton47.SetHeight(26);
  toolbutton47.SetHint("");
  toolbutton47.SetEnable(1);
  toolbutton47.SetVisible(1);
  toolbutton47.SetPoupMenu(NULL);
  toolbutton47.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton47_MouseButtonPress;
  toolbutton47.SetPixmapFileName("");
  CreateChild(& toolbutton47);
  //toolbutton48
  toolbutton48.SetFOwner(this);
  toolbutton48.SetName("toolbutton48");
  toolbutton48.SetTag(47);
  toolbutton48.SetX(199);
  toolbutton48.SetY(143);
  toolbutton48.SetWidth(26);
  toolbutton48.SetHeight(26);
  toolbutton48.SetHint("");
  toolbutton48.SetEnable(1);
  toolbutton48.SetVisible(1);
  toolbutton48.SetPoupMenu(NULL);
  toolbutton48.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton48_MouseButtonPress;
  toolbutton48.SetPixmapFileName("");
  CreateChild(& toolbutton48);
  //toolbutton49
  toolbutton49.SetFOwner(this);
  toolbutton49.SetName("toolbutton49");
  toolbutton49.SetTag(48);
  toolbutton49.SetX(226);
  toolbutton49.SetY(143);
  toolbutton49.SetWidth(26);
  toolbutton49.SetHeight(26);
  toolbutton49.SetHint("");
  toolbutton49.SetEnable(1);
  toolbutton49.SetVisible(1);
  toolbutton49.SetPoupMenu(NULL);
  toolbutton49.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton49_MouseButtonPress;
  toolbutton49.SetPixmapFileName("");
  CreateChild(& toolbutton49);
  //toolbutton50
  toolbutton50.SetFOwner(this);
  toolbutton50.SetName("toolbutton50");
  toolbutton50.SetTag(49);
  toolbutton50.SetX(253);
  toolbutton50.SetY(143);
  toolbutton50.SetWidth(26);
  toolbutton50.SetHeight(26);
  toolbutton50.SetHint("");
  toolbutton50.SetEnable(1);
  toolbutton50.SetVisible(1);
  toolbutton50.SetPoupMenu(NULL);
  toolbutton50.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton50_MouseButtonPress;
  toolbutton50.SetPixmapFileName("");
  CreateChild(& toolbutton50);
  //toolbutton51
  toolbutton51.SetFOwner(this);
  toolbutton51.SetName("toolbutton51");
  toolbutton51.SetTag(50);
  toolbutton51.SetX(10);
  toolbutton51.SetY(170);
  toolbutton51.SetWidth(26);
  toolbutton51.SetHeight(26);
  toolbutton51.SetHint("");
  toolbutton51.SetEnable(1);
  toolbutton51.SetVisible(1);
  toolbutton51.SetPoupMenu(NULL);
  toolbutton51.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton51_MouseButtonPress;
  toolbutton51.SetPixmapFileName("");
  CreateChild(& toolbutton51);
  //toolbutton52
  toolbutton52.SetFOwner(this);
  toolbutton52.SetName("toolbutton52");
  toolbutton52.SetTag(51);
  toolbutton52.SetX(37);
  toolbutton52.SetY(170);
  toolbutton52.SetWidth(26);
  toolbutton52.SetHeight(26);
  toolbutton52.SetHint("");
  toolbutton52.SetEnable(1);
  toolbutton52.SetVisible(1);
  toolbutton52.SetPoupMenu(NULL);
  toolbutton52.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton52_MouseButtonPress;
  toolbutton52.SetPixmapFileName("");
  CreateChild(& toolbutton52);
  //toolbutton53
  toolbutton53.SetFOwner(this);
  toolbutton53.SetName("toolbutton53");
  toolbutton53.SetTag(52);
  toolbutton53.SetX(64);
  toolbutton53.SetY(170);
  toolbutton53.SetWidth(26);
  toolbutton53.SetHeight(26);
  toolbutton53.SetHint("");
  toolbutton53.SetEnable(1);
  toolbutton53.SetVisible(1);
  toolbutton53.SetPoupMenu(NULL);
  toolbutton53.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton53_MouseButtonPress;
  toolbutton53.SetPixmapFileName("");
  CreateChild(& toolbutton53);
  //toolbutton54
  toolbutton54.SetFOwner(this);
  toolbutton54.SetName("toolbutton54");
  toolbutton54.SetTag(53);
  toolbutton54.SetX(91);
  toolbutton54.SetY(170);
  toolbutton54.SetWidth(26);
  toolbutton54.SetHeight(26);
  toolbutton54.SetHint("");
  toolbutton54.SetEnable(1);
  toolbutton54.SetVisible(1);
  toolbutton54.SetPoupMenu(NULL);
  toolbutton54.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton54_MouseButtonPress;
  toolbutton54.SetPixmapFileName("");
  CreateChild(& toolbutton54);
  //toolbutton55
  toolbutton55.SetFOwner(this);
  toolbutton55.SetName("toolbutton55");
  toolbutton55.SetTag(54);
  toolbutton55.SetX(118);
  toolbutton55.SetY(170);
  toolbutton55.SetWidth(26);
  toolbutton55.SetHeight(26);
  toolbutton55.SetHint("");
  toolbutton55.SetEnable(1);
  toolbutton55.SetVisible(1);
  toolbutton55.SetPoupMenu(NULL);
  toolbutton55.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton55_MouseButtonPress;
  toolbutton55.SetPixmapFileName("");
  CreateChild(& toolbutton55);
  //toolbutton56
  toolbutton56.SetFOwner(this);
  toolbutton56.SetName("toolbutton56");
  toolbutton56.SetTag(55);
  toolbutton56.SetX(145);
  toolbutton56.SetY(170);
  toolbutton56.SetWidth(26);
  toolbutton56.SetHeight(26);
  toolbutton56.SetHint("");
  toolbutton56.SetEnable(1);
  toolbutton56.SetVisible(1);
  toolbutton56.SetPoupMenu(NULL);
  toolbutton56.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton56_MouseButtonPress;
  toolbutton56.SetPixmapFileName("");
  CreateChild(& toolbutton56);
  //toolbutton57
  toolbutton57.SetFOwner(this);
  toolbutton57.SetName("toolbutton57");
  toolbutton57.SetTag(56);
  toolbutton57.SetX(172);
  toolbutton57.SetY(170);
  toolbutton57.SetWidth(26);
  toolbutton57.SetHeight(26);
  toolbutton57.SetHint("");
  toolbutton57.SetEnable(1);
  toolbutton57.SetVisible(1);
  toolbutton57.SetPoupMenu(NULL);
  toolbutton57.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton57_MouseButtonPress;
  toolbutton57.SetPixmapFileName("");
  CreateChild(& toolbutton57);
  //toolbutton58
  toolbutton58.SetFOwner(this);
  toolbutton58.SetName("toolbutton58");
  toolbutton58.SetTag(57);
  toolbutton58.SetX(199);
  toolbutton58.SetY(170);
  toolbutton58.SetWidth(26);
  toolbutton58.SetHeight(26);
  toolbutton58.SetHint("");
  toolbutton58.SetEnable(1);
  toolbutton58.SetVisible(1);
  toolbutton58.SetPoupMenu(NULL);
  toolbutton58.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton58_MouseButtonPress;
  toolbutton58.SetPixmapFileName("");
  CreateChild(& toolbutton58);
  //toolbutton59
  toolbutton59.SetFOwner(this);
  toolbutton59.SetName("toolbutton59");
  toolbutton59.SetTag(58);
  toolbutton59.SetX(226);
  toolbutton59.SetY(170);
  toolbutton59.SetWidth(26);
  toolbutton59.SetHeight(26);
  toolbutton59.SetHint("");
  toolbutton59.SetEnable(1);
  toolbutton59.SetVisible(1);
  toolbutton59.SetPoupMenu(NULL);
  toolbutton59.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton59_MouseButtonPress;
  toolbutton59.SetPixmapFileName("");
  CreateChild(& toolbutton59);
  //toolbutton60
  toolbutton60.SetFOwner(this);
  toolbutton60.SetName("toolbutton60");
  toolbutton60.SetTag(59);
  toolbutton60.SetX(253);
  toolbutton60.SetY(170);
  toolbutton60.SetWidth(26);
  toolbutton60.SetHeight(26);
  toolbutton60.SetHint("");
  toolbutton60.SetEnable(1);
  toolbutton60.SetVisible(1);
  toolbutton60.SetPoupMenu(NULL);
  toolbutton60.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton60_MouseButtonPress;
  toolbutton60.SetPixmapFileName("");
  CreateChild(& toolbutton60);
  //toolbutton61
  toolbutton61.SetFOwner(this);
  toolbutton61.SetName("toolbutton61");
  toolbutton61.SetTag(60);
  toolbutton61.SetX(10);
  toolbutton61.SetY(197);
  toolbutton61.SetWidth(26);
  toolbutton61.SetHeight(26);
  toolbutton61.SetHint("");
  toolbutton61.SetEnable(1);
  toolbutton61.SetVisible(1);
  toolbutton61.SetPoupMenu(NULL);
  toolbutton61.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton61_MouseButtonPress;
  toolbutton61.SetPixmapFileName("");
  CreateChild(& toolbutton61);
  //toolbutton62
  toolbutton62.SetFOwner(this);
  toolbutton62.SetName("toolbutton62");
  toolbutton62.SetTag(61);
  toolbutton62.SetX(37);
  toolbutton62.SetY(197);
  toolbutton62.SetWidth(26);
  toolbutton62.SetHeight(26);
  toolbutton62.SetHint("");
  toolbutton62.SetEnable(1);
  toolbutton62.SetVisible(1);
  toolbutton62.SetPoupMenu(NULL);
  toolbutton62.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton62_MouseButtonPress;
  toolbutton62.SetPixmapFileName("");
  CreateChild(& toolbutton62);
  //toolbutton63
  toolbutton63.SetFOwner(this);
  toolbutton63.SetName("toolbutton63");
  toolbutton63.SetTag(62);
  toolbutton63.SetX(64);
  toolbutton63.SetY(197);
  toolbutton63.SetWidth(26);
  toolbutton63.SetHeight(26);
  toolbutton63.SetHint("");
  toolbutton63.SetEnable(1);
  toolbutton63.SetVisible(1);
  toolbutton63.SetPoupMenu(NULL);
  toolbutton63.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton63_MouseButtonPress;
  toolbutton63.SetPixmapFileName("");
  CreateChild(& toolbutton63);
  //toolbutton64
  toolbutton64.SetFOwner(this);
  toolbutton64.SetName("toolbutton64");
  toolbutton64.SetTag(63);
  toolbutton64.SetX(91);
  toolbutton64.SetY(197);
  toolbutton64.SetWidth(26);
  toolbutton64.SetHeight(26);
  toolbutton64.SetHint("");
  toolbutton64.SetEnable(1);
  toolbutton64.SetVisible(1);
  toolbutton64.SetPoupMenu(NULL);
  toolbutton64.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton64_MouseButtonPress;
  toolbutton64.SetPixmapFileName("");
  CreateChild(& toolbutton64);
  //toolbutton65
  toolbutton65.SetFOwner(this);
  toolbutton65.SetName("toolbutton65");
  toolbutton65.SetTag(64);
  toolbutton65.SetX(118);
  toolbutton65.SetY(197);
  toolbutton65.SetWidth(26);
  toolbutton65.SetHeight(26);
  toolbutton65.SetHint("");
  toolbutton65.SetEnable(1);
  toolbutton65.SetVisible(1);
  toolbutton65.SetPoupMenu(NULL);
  toolbutton65.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton65_MouseButtonPress;
  toolbutton65.SetPixmapFileName("");
  CreateChild(& toolbutton65);
  //toolbutton66
  toolbutton66.SetFOwner(this);
  toolbutton66.SetName("toolbutton66");
  toolbutton66.SetTag(65);
  toolbutton66.SetX(145);
  toolbutton66.SetY(197);
  toolbutton66.SetWidth(26);
  toolbutton66.SetHeight(26);
  toolbutton66.SetHint("");
  toolbutton66.SetEnable(1);
  toolbutton66.SetVisible(1);
  toolbutton66.SetPoupMenu(NULL);
  toolbutton66.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton66_MouseButtonPress;
  toolbutton66.SetPixmapFileName("");
  CreateChild(& toolbutton66);
  //toolbutton67
  toolbutton67.SetFOwner(this);
  toolbutton67.SetName("toolbutton67");
  toolbutton67.SetTag(66);
  toolbutton67.SetX(172);
  toolbutton67.SetY(197);
  toolbutton67.SetWidth(26);
  toolbutton67.SetHeight(26);
  toolbutton67.SetHint("");
  toolbutton67.SetEnable(1);
  toolbutton67.SetVisible(1);
  toolbutton67.SetPoupMenu(NULL);
  toolbutton67.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton67_MouseButtonPress;
  toolbutton67.SetPixmapFileName("");
  CreateChild(& toolbutton67);
  //toolbutton68
  toolbutton68.SetFOwner(this);
  toolbutton68.SetName("toolbutton68");
  toolbutton68.SetTag(67);
  toolbutton68.SetX(199);
  toolbutton68.SetY(197);
  toolbutton68.SetWidth(26);
  toolbutton68.SetHeight(26);
  toolbutton68.SetHint("");
  toolbutton68.SetEnable(1);
  toolbutton68.SetVisible(1);
  toolbutton68.SetPoupMenu(NULL);
  toolbutton68.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton68_MouseButtonPress;
  toolbutton68.SetPixmapFileName("");
  CreateChild(& toolbutton68);
  //toolbutton69
  toolbutton69.SetFOwner(this);
  toolbutton69.SetName("toolbutton69");
  toolbutton69.SetTag(68);
  toolbutton69.SetX(226);
  toolbutton69.SetY(197);
  toolbutton69.SetWidth(26);
  toolbutton69.SetHeight(26);
  toolbutton69.SetHint("");
  toolbutton69.SetEnable(1);
  toolbutton69.SetVisible(1);
  toolbutton69.SetPoupMenu(NULL);
  toolbutton69.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton69_MouseButtonPress;
  toolbutton69.SetPixmapFileName("");
  CreateChild(& toolbutton69);
  //toolbutton70
  toolbutton70.SetFOwner(this);
  toolbutton70.SetName("toolbutton70");
  toolbutton70.SetTag(69);
  toolbutton70.SetX(253);
  toolbutton70.SetY(197);
  toolbutton70.SetWidth(26);
  toolbutton70.SetHeight(26);
  toolbutton70.SetHint("");
  toolbutton70.SetEnable(1);
  toolbutton70.SetVisible(1);
  toolbutton70.SetPoupMenu(NULL);
  toolbutton70.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton70_MouseButtonPress;
  toolbutton70.SetPixmapFileName("");
  CreateChild(& toolbutton70);
  //toolbutton71
  toolbutton71.SetFOwner(this);
  toolbutton71.SetName("toolbutton71");
  toolbutton71.SetTag(70);
  toolbutton71.SetX(10);
  toolbutton71.SetY(224);
  toolbutton71.SetWidth(26);
  toolbutton71.SetHeight(26);
  toolbutton71.SetHint("");
  toolbutton71.SetEnable(1);
  toolbutton71.SetVisible(1);
  toolbutton71.SetPoupMenu(NULL);
  toolbutton71.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton71_MouseButtonPress;
  toolbutton71.SetPixmapFileName("");
  CreateChild(& toolbutton71);
  //toolbutton72
  toolbutton72.SetFOwner(this);
  toolbutton72.SetName("toolbutton72");
  toolbutton72.SetTag(71);
  toolbutton72.SetX(37);
  toolbutton72.SetY(224);
  toolbutton72.SetWidth(26);
  toolbutton72.SetHeight(26);
  toolbutton72.SetHint("");
  toolbutton72.SetEnable(1);
  toolbutton72.SetVisible(1);
  toolbutton72.SetPoupMenu(NULL);
  toolbutton72.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton72_MouseButtonPress;
  toolbutton72.SetPixmapFileName("");
  CreateChild(& toolbutton72);
  //toolbutton73
  toolbutton73.SetFOwner(this);
  toolbutton73.SetName("toolbutton73");
  toolbutton73.SetTag(72);
  toolbutton73.SetX(64);
  toolbutton73.SetY(224);
  toolbutton73.SetWidth(26);
  toolbutton73.SetHeight(26);
  toolbutton73.SetHint("");
  toolbutton73.SetEnable(1);
  toolbutton73.SetVisible(1);
  toolbutton73.SetPoupMenu(NULL);
  toolbutton73.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton73_MouseButtonPress;
  toolbutton73.SetPixmapFileName("");
  CreateChild(& toolbutton73);
  //toolbutton74
  toolbutton74.SetFOwner(this);
  toolbutton74.SetName("toolbutton74");
  toolbutton74.SetTag(73);
  toolbutton74.SetX(91);
  toolbutton74.SetY(224);
  toolbutton74.SetWidth(26);
  toolbutton74.SetHeight(26);
  toolbutton74.SetHint("");
  toolbutton74.SetEnable(1);
  toolbutton74.SetVisible(1);
  toolbutton74.SetPoupMenu(NULL);
  toolbutton74.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton74_MouseButtonPress;
  toolbutton74.SetPixmapFileName("");
  CreateChild(& toolbutton74);
  //toolbutton75
  toolbutton75.SetFOwner(this);
  toolbutton75.SetName("toolbutton75");
  toolbutton75.SetTag(74);
  toolbutton75.SetX(118);
  toolbutton75.SetY(224);
  toolbutton75.SetWidth(26);
  toolbutton75.SetHeight(26);
  toolbutton75.SetHint("");
  toolbutton75.SetEnable(1);
  toolbutton75.SetVisible(1);
  toolbutton75.SetPoupMenu(NULL);
  toolbutton75.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton75_MouseButtonPress;
  toolbutton75.SetPixmapFileName("");
  CreateChild(& toolbutton75);
  //toolbutton76
  toolbutton76.SetFOwner(this);
  toolbutton76.SetName("toolbutton76");
  toolbutton76.SetTag(75);
  toolbutton76.SetX(145);
  toolbutton76.SetY(224);
  toolbutton76.SetWidth(26);
  toolbutton76.SetHeight(26);
  toolbutton76.SetHint("");
  toolbutton76.SetEnable(1);
  toolbutton76.SetVisible(1);
  toolbutton76.SetPoupMenu(NULL);
  toolbutton76.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton76_MouseButtonPress;
  toolbutton76.SetPixmapFileName("");
  CreateChild(& toolbutton76);
  //toolbutton77
  toolbutton77.SetFOwner(this);
  toolbutton77.SetName("toolbutton77");
  toolbutton77.SetTag(76);
  toolbutton77.SetX(172);
  toolbutton77.SetY(224);
  toolbutton77.SetWidth(26);
  toolbutton77.SetHeight(26);
  toolbutton77.SetHint("");
  toolbutton77.SetEnable(1);
  toolbutton77.SetVisible(1);
  toolbutton77.SetPoupMenu(NULL);
  toolbutton77.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton77_MouseButtonPress;
  toolbutton77.SetPixmapFileName("");
  CreateChild(& toolbutton77);
  //toolbutton78
  toolbutton78.SetFOwner(this);
  toolbutton78.SetName("toolbutton78");
  toolbutton78.SetTag(77);
  toolbutton78.SetX(199);
  toolbutton78.SetY(224);
  toolbutton78.SetWidth(26);
  toolbutton78.SetHeight(26);
  toolbutton78.SetHint("");
  toolbutton78.SetEnable(1);
  toolbutton78.SetVisible(1);
  toolbutton78.SetPoupMenu(NULL);
  toolbutton78.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton78_MouseButtonPress;
  toolbutton78.SetPixmapFileName("");
  CreateChild(& toolbutton78);
  //toolbutton79
  toolbutton79.SetFOwner(this);
  toolbutton79.SetName("toolbutton79");
  toolbutton79.SetTag(78);
  toolbutton79.SetX(226);
  toolbutton79.SetY(224);
  toolbutton79.SetWidth(26);
  toolbutton79.SetHeight(26);
  toolbutton79.SetHint("");
  toolbutton79.SetEnable(1);
  toolbutton79.SetVisible(1);
  toolbutton79.SetPoupMenu(NULL);
  toolbutton79.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton79_MouseButtonPress;
  toolbutton79.SetPixmapFileName("");
  CreateChild(& toolbutton79);
  //toolbutton80
  toolbutton80.SetFOwner(this);
  toolbutton80.SetName("toolbutton80");
  toolbutton80.SetTag(79);
  toolbutton80.SetX(253);
  toolbutton80.SetY(224);
  toolbutton80.SetWidth(26);
  toolbutton80.SetHeight(26);
  toolbutton80.SetHint("");
  toolbutton80.SetEnable(1);
  toolbutton80.SetVisible(1);
  toolbutton80.SetPoupMenu(NULL);
  toolbutton80.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton80_MouseButtonPress;
  toolbutton80.SetPixmapFileName("");
  CreateChild(& toolbutton80);
  //toolbutton81
  toolbutton81.SetFOwner(this);
  toolbutton81.SetName("toolbutton81");
  toolbutton81.SetTag(80);
  toolbutton81.SetX(10);
  toolbutton81.SetY(251);
  toolbutton81.SetWidth(26);
  toolbutton81.SetHeight(26);
  toolbutton81.SetHint("");
  toolbutton81.SetEnable(1);
  toolbutton81.SetVisible(1);
  toolbutton81.SetPoupMenu(NULL);
  toolbutton81.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton81_MouseButtonPress;
  toolbutton81.SetPixmapFileName("");
  CreateChild(& toolbutton81);
  //toolbutton82
  toolbutton82.SetFOwner(this);
  toolbutton82.SetName("toolbutton82");
  toolbutton82.SetTag(81);
  toolbutton82.SetX(37);
  toolbutton82.SetY(251);
  toolbutton82.SetWidth(26);
  toolbutton82.SetHeight(26);
  toolbutton82.SetHint("");
  toolbutton82.SetEnable(1);
  toolbutton82.SetVisible(1);
  toolbutton82.SetPoupMenu(NULL);
  toolbutton82.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton82_MouseButtonPress;
  toolbutton82.SetPixmapFileName("");
  CreateChild(& toolbutton82);
  //toolbutton83
  toolbutton83.SetFOwner(this);
  toolbutton83.SetName("toolbutton83");
  toolbutton83.SetTag(82);
  toolbutton83.SetX(64);
  toolbutton83.SetY(251);
  toolbutton83.SetWidth(26);
  toolbutton83.SetHeight(26);
  toolbutton83.SetHint("");
  toolbutton83.SetEnable(1);
  toolbutton83.SetVisible(1);
  toolbutton83.SetPoupMenu(NULL);
  toolbutton83.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton83_MouseButtonPress;
  toolbutton83.SetPixmapFileName("");
  CreateChild(& toolbutton83);
  //toolbutton84
  toolbutton84.SetFOwner(this);
  toolbutton84.SetName("toolbutton84");
  toolbutton84.SetTag(83);
  toolbutton84.SetX(91);
  toolbutton84.SetY(251);
  toolbutton84.SetWidth(26);
  toolbutton84.SetHeight(26);
  toolbutton84.SetHint("");
  toolbutton84.SetEnable(1);
  toolbutton84.SetVisible(1);
  toolbutton84.SetPoupMenu(NULL);
  toolbutton84.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton84_MouseButtonPress;
  toolbutton84.SetPixmapFileName("");
  CreateChild(& toolbutton84);
  //toolbutton85
  toolbutton85.SetFOwner(this);
  toolbutton85.SetName("toolbutton85");
  toolbutton85.SetTag(84);
  toolbutton85.SetX(118);
  toolbutton85.SetY(251);
  toolbutton85.SetWidth(26);
  toolbutton85.SetHeight(26);
  toolbutton85.SetHint("");
  toolbutton85.SetEnable(1);
  toolbutton85.SetVisible(1);
  toolbutton85.SetPoupMenu(NULL);
  toolbutton85.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton85_MouseButtonPress;
  toolbutton85.SetPixmapFileName("");
  CreateChild(& toolbutton85);
  //toolbutton86
  toolbutton86.SetFOwner(this);
  toolbutton86.SetName("toolbutton86");
  toolbutton86.SetTag(85);
  toolbutton86.SetX(145);
  toolbutton86.SetY(251);
  toolbutton86.SetWidth(26);
  toolbutton86.SetHeight(26);
  toolbutton86.SetHint("");
  toolbutton86.SetEnable(1);
  toolbutton86.SetVisible(1);
  toolbutton86.SetPoupMenu(NULL);
  toolbutton86.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton86_MouseButtonPress;
  toolbutton86.SetPixmapFileName("");
  CreateChild(& toolbutton86);
  //toolbutton87
  toolbutton87.SetFOwner(this);
  toolbutton87.SetName("toolbutton87");
  toolbutton87.SetTag(86);
  toolbutton87.SetX(172);
  toolbutton87.SetY(251);
  toolbutton87.SetWidth(26);
  toolbutton87.SetHeight(26);
  toolbutton87.SetHint("");
  toolbutton87.SetEnable(1);
  toolbutton87.SetVisible(1);
  toolbutton87.SetPoupMenu(NULL);
  toolbutton87.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton87_MouseButtonPress;
  toolbutton87.SetPixmapFileName("");
  CreateChild(& toolbutton87);
  //toolbutton88
  toolbutton88.SetFOwner(this);
  toolbutton88.SetName("toolbutton88");
  toolbutton88.SetTag(87);
  toolbutton88.SetX(199);
  toolbutton88.SetY(251);
  toolbutton88.SetWidth(26);
  toolbutton88.SetHeight(26);
  toolbutton88.SetHint("");
  toolbutton88.SetEnable(1);
  toolbutton88.SetVisible(1);
  toolbutton88.SetPoupMenu(NULL);
  toolbutton88.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton88_MouseButtonPress;
  toolbutton88.SetPixmapFileName("");
  CreateChild(& toolbutton88);
  //toolbutton89
  toolbutton89.SetFOwner(this);
  toolbutton89.SetName("toolbutton89");
  toolbutton89.SetTag(88);
  toolbutton89.SetX(226);
  toolbutton89.SetY(251);
  toolbutton89.SetWidth(26);
  toolbutton89.SetHeight(26);
  toolbutton89.SetHint("");
  toolbutton89.SetEnable(1);
  toolbutton89.SetVisible(1);
  toolbutton89.SetPoupMenu(NULL);
  toolbutton89.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton89_MouseButtonPress;
  toolbutton89.SetPixmapFileName("");
  CreateChild(& toolbutton89);
  //toolbutton90
  toolbutton90.SetFOwner(this);
  toolbutton90.SetName("toolbutton90");
  toolbutton90.SetTag(89);
  toolbutton90.SetX(253);
  toolbutton90.SetY(251);
  toolbutton90.SetWidth(26);
  toolbutton90.SetHeight(26);
  toolbutton90.SetHint("");
  toolbutton90.SetEnable(1);
  toolbutton90.SetVisible(1);
  toolbutton90.SetPoupMenu(NULL);
  toolbutton90.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton90_MouseButtonPress;
  toolbutton90.SetPixmapFileName("");
  CreateChild(& toolbutton90);
  //toolbutton91
  toolbutton91.SetFOwner(this);
  toolbutton91.SetName("toolbutton91");
  toolbutton91.SetTag(90);
  toolbutton91.SetX(10);
  toolbutton91.SetY(278);
  toolbutton91.SetWidth(26);
  toolbutton91.SetHeight(26);
  toolbutton91.SetHint("");
  toolbutton91.SetEnable(1);
  toolbutton91.SetVisible(1);
  toolbutton91.SetPoupMenu(NULL);
  toolbutton91.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton91_MouseButtonPress;
  toolbutton91.SetPixmapFileName("");
  CreateChild(& toolbutton91);
  //toolbutton92
  toolbutton92.SetFOwner(this);
  toolbutton92.SetName("toolbutton92");
  toolbutton92.SetTag(91);
  toolbutton92.SetX(37);
  toolbutton92.SetY(278);
  toolbutton92.SetWidth(26);
  toolbutton92.SetHeight(26);
  toolbutton92.SetHint("");
  toolbutton92.SetEnable(1);
  toolbutton92.SetVisible(1);
  toolbutton92.SetPoupMenu(NULL);
  toolbutton92.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton92_MouseButtonPress;
  toolbutton92.SetPixmapFileName("");
  CreateChild(& toolbutton92);
  //toolbutton93
  toolbutton93.SetFOwner(this);
  toolbutton93.SetName("toolbutton93");
  toolbutton93.SetTag(92);
  toolbutton93.SetX(64);
  toolbutton93.SetY(278);
  toolbutton93.SetWidth(26);
  toolbutton93.SetHeight(26);
  toolbutton93.SetHint("");
  toolbutton93.SetEnable(1);
  toolbutton93.SetVisible(1);
  toolbutton93.SetPoupMenu(NULL);
  toolbutton93.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton93_MouseButtonPress;
  toolbutton93.SetPixmapFileName("");
  CreateChild(& toolbutton93);
  //toolbutton94
  toolbutton94.SetFOwner(this);
  toolbutton94.SetName("toolbutton94");
  toolbutton94.SetTag(93);
  toolbutton94.SetX(91);
  toolbutton94.SetY(278);
  toolbutton94.SetWidth(26);
  toolbutton94.SetHeight(26);
  toolbutton94.SetHint("");
  toolbutton94.SetEnable(1);
  toolbutton94.SetVisible(1);
  toolbutton94.SetPoupMenu(NULL);
  toolbutton94.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton94_MouseButtonPress;
  toolbutton94.SetPixmapFileName("");
  CreateChild(& toolbutton94);
  //toolbutton95
  toolbutton95.SetFOwner(this);
  toolbutton95.SetName("toolbutton95");
  toolbutton95.SetTag(94);
  toolbutton95.SetX(118);
  toolbutton95.SetY(278);
  toolbutton95.SetWidth(26);
  toolbutton95.SetHeight(26);
  toolbutton95.SetHint("");
  toolbutton95.SetEnable(1);
  toolbutton95.SetVisible(1);
  toolbutton95.SetPoupMenu(NULL);
  toolbutton95.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton95_MouseButtonPress;
  toolbutton95.SetPixmapFileName("");
  CreateChild(& toolbutton95);
  //toolbutton96
  toolbutton96.SetFOwner(this);
  toolbutton96.SetName("toolbutton96");
  toolbutton96.SetTag(95);
  toolbutton96.SetX(145);
  toolbutton96.SetY(278);
  toolbutton96.SetWidth(26);
  toolbutton96.SetHeight(26);
  toolbutton96.SetHint("");
  toolbutton96.SetEnable(1);
  toolbutton96.SetVisible(1);
  toolbutton96.SetPoupMenu(NULL);
  toolbutton96.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton96_MouseButtonPress;
  toolbutton96.SetPixmapFileName("");
  CreateChild(& toolbutton96);
  //toolbutton97
  toolbutton97.SetFOwner(this);
  toolbutton97.SetName("toolbutton97");
  toolbutton97.SetTag(96);
  toolbutton97.SetX(172);
  toolbutton97.SetY(278);
  toolbutton97.SetWidth(26);
  toolbutton97.SetHeight(26);
  toolbutton97.SetHint("");
  toolbutton97.SetEnable(1);
  toolbutton97.SetVisible(1);
  toolbutton97.SetPoupMenu(NULL);
  toolbutton97.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton97_MouseButtonPress;
  toolbutton97.SetPixmapFileName("");
  CreateChild(& toolbutton97);
  //toolbutton98
  toolbutton98.SetFOwner(this);
  toolbutton98.SetName("toolbutton98");
  toolbutton98.SetTag(97);
  toolbutton98.SetX(199);
  toolbutton98.SetY(278);
  toolbutton98.SetWidth(26);
  toolbutton98.SetHeight(26);
  toolbutton98.SetHint("");
  toolbutton98.SetEnable(1);
  toolbutton98.SetVisible(1);
  toolbutton98.SetPoupMenu(NULL);
  toolbutton98.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton98_MouseButtonPress;
  toolbutton98.SetPixmapFileName("");
  CreateChild(& toolbutton98);
  //toolbutton99
  toolbutton99.SetFOwner(this);
  toolbutton99.SetName("toolbutton99");
  toolbutton99.SetTag(98);
  toolbutton99.SetX(226);
  toolbutton99.SetY(278);
  toolbutton99.SetWidth(26);
  toolbutton99.SetHeight(26);
  toolbutton99.SetHint("");
  toolbutton99.SetEnable(1);
  toolbutton99.SetVisible(1);
  toolbutton99.SetPoupMenu(NULL);
  toolbutton99.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton99_MouseButtonPress;
  toolbutton99.SetPixmapFileName("");
  CreateChild(& toolbutton99);
  //toolbutton100
  toolbutton100.SetFOwner(this);
  toolbutton100.SetName("toolbutton100");
  toolbutton100.SetTag(99);
  toolbutton100.SetX(253);
  toolbutton100.SetY(278);
  toolbutton100.SetWidth(26);
  toolbutton100.SetHeight(26);
  toolbutton100.SetHint("");
  toolbutton100.SetEnable(1);
  toolbutton100.SetVisible(1);
  toolbutton100.SetPoupMenu(NULL);
  toolbutton100.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::toolbutton100_MouseButtonPress;
  toolbutton100.SetPixmapFileName("");
  CreateChild(& toolbutton100);
  //menu1
  menu1.SetFOwner(this);
  menu1.SetName("menu1");
  menu1.SetTag(0);
  menu1.SetX(0);
  menu1.SetY(0);
  menu1.SetWidth(290);
  menu1.SetHeight(25);
  menu1.SetHint("");
  menu1.SetEnable(1);
  menu1.SetVisible(1);
  menu1.SetMenuItens("Arquivo,Limpar,Sobre,");
  CreateChild(& menu1);
  //menu1_Arquivo
  menu1_Arquivo.SetFOwner(this);
  menu1_Arquivo.SetName("menu1_Arquivo");
  menu1_Arquivo.SetTag(0);
  menu1_Arquivo.SetText("Arquivo");
  menu1_Arquivo.SetSubMenu(&pmenu1);
  menu1.CreateChild(& menu1_Arquivo);
  //menu1_Limpar
  menu1_Limpar.SetFOwner(this);
  menu1_Limpar.SetName("menu1_Limpar");
  menu1_Limpar.SetTag(0);
  menu1_Limpar.SetText("Limpar");
  menu1_Limpar.SetSubMenu(NULL);
  menu1_Limpar.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::menu1_Limpar_MouseButtonPress;
  menu1.CreateChild(& menu1_Limpar);
  //menu1_Sobre
  menu1_Sobre.SetFOwner(this);
  menu1_Sobre.SetName("menu1_Sobre");
  menu1_Sobre.SetTag(0);
  menu1_Sobre.SetText("Sobre");
  menu1_Sobre.SetSubMenu(NULL);
  menu1_Sobre.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::menu1_Sobre_MouseButtonPress;
  menu1.CreateChild(& menu1_Sobre);
  //pmenu1_Abrir
  pmenu1_Abrir.SetFOwner(this);
  pmenu1_Abrir.SetName("pmenu1_Abrir");
  pmenu1_Abrir.SetTag(0);
  pmenu1_Abrir.SetText("Abrir");
  pmenu1_Abrir.SetSubMenu(NULL);
  pmenu1_Abrir.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::pmenu1_Abrir_MouseButtonPress;
  pmenu1.CreateChild(& pmenu1_Abrir);
  //pmenu1_Salvar
  pmenu1_Salvar.SetFOwner(this);
  pmenu1_Salvar.SetName("pmenu1_Salvar");
  pmenu1_Salvar.SetTag(0);
  pmenu1_Salvar.SetText("Salvar");
  pmenu1_Salvar.SetSubMenu(NULL);
  pmenu1_Salvar.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::pmenu1_Salvar_MouseButtonPress;
  pmenu1.CreateChild(& pmenu1_Salvar);
  //pmenu1_Sair
  pmenu1_Sair.SetFOwner(this);
  pmenu1_Sair.SetName("pmenu1_Sair");
  pmenu1_Sair.SetTag(0);
  pmenu1_Sair.SetText("Sair");
  pmenu1_Sair.SetSubMenu(NULL);
  pmenu1_Sair.MouseButtonPress=MOUSEBUTTONPRESS & CWindow1::pmenu1_Sair_MouseButtonPress;
  pmenu1.CreateChild(& pmenu1_Sair);
  //abrirdialog
  abrirdialog.SetFOwner(this);
  abrirdialog.SetName("abrirdialog");
  abrirdialog.SetTag(0);
  abrirdialog.SetX(100);
  abrirdialog.SetY(100);
  abrirdialog.SetWidth(200);
  abrirdialog.SetHeight(250);
  abrirdialog.SetHint("");
  abrirdialog.SetEnable(1);
  abrirdialog.SetVisible(0);
  abrirdialog.SetPoupMenu(NULL);
  CreateChild(& abrirdialog);
  //salvardialog
  salvardialog.SetFOwner(this);
  salvardialog.SetName("salvardialog");
  salvardialog.SetTag(0);
  salvardialog.SetX(100);
  salvardialog.SetY(100);
  salvardialog.SetWidth(200);
  salvardialog.SetHeight(250);
  salvardialog.SetHint("");
  salvardialog.SetEnable(1);
  salvardialog.SetVisible(0);
  salvardialog.SetPoupMenu(NULL);
  CreateChild(& salvardialog);
};
